### ISSUE TITLE
Исправление буквы и возможность получения ОКАТО и ОГРН

### ISSUE THREAD

**Issue by WIN4ig** [li0ard/oms-barcode#1]
В листе charTable буква "E" латинская, а не кириллическая. Так же бы хотелось, чтобы была функция получения номера ОКАТО и ОГРН.

**Comment by li0ard** [comment]
Букву исправлю, а насчет ОКАТО и ОГРН то во 2 версии штрихкода эти поля были убраны и сейчас не используются, поэтому я не вижу смысла реализовывать это
